### ISSUE TITLE
How to connect with my EV3 brick using USB?

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev-lang#102]
Hi a I am newbie developer with EV3Dev.

If I connect the brick using a USB.
What is the IP used to make a ssh connection?

Many thanks in advance

Juan Antonio

**Comment by ddemidov** [comment]
Hi,

Did you have a look at http://www.ev3dev.org/docs/tutorials/connecting-to-the-internet-via-usb/?

**Comment by jabrena** [comment]
I will read tonight.

Many thanks @ddemidov

**Comment by jabrena** [comment]
Connected.
