### ISSUE TITLE
Does exist a Java example for EV3Dev?

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev-lang#111]
Hi,

anyone has tested EV3Dev with Java?

Cheers

Juan Antonio

**Comment by ddemidov** [comment]
Not that I know of. And its not listed on the [libraries](http://www.ev3dev.org/docs/libraries) page, so I guess it does not exist.

**Comment by jabrena** [comment]
Yes, but i say an isolate example using the debian package.

``` java

public class HelloWorld {

    public static void main(String[] args) {
        // Prints "Hello, World" to the terminal window.
        System.out.println("Hello, World");
    }

}

```

**Comment by ddemidov** [comment]
That should be possible as long as you install some implementation of java runtime.

**Comment by jabrena** [comment]
I will try to test today.

Many thanks @ddemidov 

Cheers

**Comment by jabrena** [comment]
Good night @ddemidov , I tested Java with EV3Dev without any problem.
This evening, I will try to define some issues to build a binding to Java as you do with Python.
https://github.com/jabrena/ev3dev-lang-java/

Cheers

**Comment by jabrena** [comment]
https://github.com/jabrena/ev3dev-lang-java/issues/3
