### ISSUE TITLE
How to create spec.json

### ISSUE THREAD

**Issue by rhempel** [ev3dev/ev3dev-lang#150]
I must have missed something, but do we generate `spec.json` manually or from the kernel source? I'm asking because I'm about to squash the tacho motor changes for the PR and need to test the new attribute(s) for linear motors

**Comment by ddemidov** [comment]
We create spec.json manually, although creating it from kernel sources could be a good idea. See #51 for discussion.

**Comment by rhempel** [comment]
Well, I'll edit it manually for the now then.
