### ISSUE TITLE
Unified language for Java - Library Submission

### ISSUE THREAD

**Issue by a1aw** [ev3dev/ev3dev-lang#157]
Hi,

I just completed the unified language library for ev3dev.

Here's the downloads, wiki and JavaDoc:
[[Unstable release Build 98]](https://github.com/mob41/ev3dev-lang-java/releases/tag/unstable-0.0.1-SNAPSHOT-B98)
[[Repository]](https://github.com/mob41/ev3dev-lang-java)
[[JavaDoc]](https://mob41.github.io/ev3dev-lang-java/javadoc)
[[Wiki]](https://github.com/mob41/ev3dev-lang-java/wiki)

Unfortunately, I haven't complete the Wiki yet as I don't have enough time, I will try to complete it tonight. And I don't have those modules like, DC/Servo motors, I2C,Gyro,Light,Sound,Ultrasonic sensors. So that I can't test with those functions

**Comment by WasabiFan** [comment]
Thanks! I'll take a look when I get some time.

Whenever we get to adding this to our language lists, I'll need to remember to explain both this and @jabrena's library and how they are different.

**Comment by WasabiFan** [comment]
Sorry, I haven't forgotten about this -- just postponed it while I got other stuff done :wink: It's tough maintaining projects on GitHub when you have "real life work" to do!

To make sure I understand, what do you want us to do as a result of this issue other than adding this library to our lists in the README and on the site?

**Comment by a1aw** [comment]
@WasabiFan Sorry for waiting for a long time for a reply. I am so, so, busy on school projects and tasks.

I don't completely understand what you mainly asking about. Are you asking me to add this to the site list and the README?

**Comment by WasabiFan** [comment]
> Sorry for waiting for a long time for a reply. I am so, so, busy on school projects and tasks.

No problem! I'm in a very similar situation myself.

> I don't completely understand what you mainly asking about. Are you asking me to add this to the site list and the README?

I was just asking what you wanted me to do. I assumed that your intent with this issue was for me to add your library to the list of "official ones" on the README and on the site, but I wanted to confirm that that was what you wanted. Is that what you want me to do (meaning that your library is ready to be promoted)? Or was there something else that you wanted us to do?

**Comment by a1aw** [comment]
...just for quick reply

Yup, you can just add the library to the list.
Besides, I will go and update the library to support kernel v10 in these
few days. Monday is holiday, yeah.

**Comment by mob41** [comment]
The library was updated to v10 now...
