### ISSUE TITLE
A question about sensor inherits

### ISSUE THREAD

**Issue by a1aw** [ev3dev/ev3dev-lang#167]
Hi,

I am quite confused what should I do with analog sensors, I2C sensor's inherits' drivers checking in [my  Java binding library](https://github.com/mob41/ev3dev-lang-java/), so I suggested to ask a question. As I2C sensor has its own `driver_name` called `nxt-i2c-sensor`, my library will check whether the user plugged in a correct device with the `driver_name`, if wrong driver, a `EV3LibraryException` exception will be thrown. But what if its inherits? 

For example, [Pixy Cmucam 5](http://www.ev3dev.org/docs/sensors/charmed-labs-pixy-cmucam5-for-lego/) sensor is a inherit of `I2CSensor`, it also has its own `driver_name` called `pixy-lego`. Similarly it will perform driver checks.

If the developer creates a `PixyCmucam5Sensor` instance, it will call the base class's (the base class is `I2CSensor`) initialization function. Just such that the developer has already set the driver as `nxt-i2c-sensor`, so that when the child class's (`PixyCmucam5Sensor`) initialization function checks the `driver_name`, it will always throw exception cause the driver is not `pixy-lego`.

The another way to solve the problem is not to perform checks on ~~child~~ classes. And sets driver automatically. Any ideas?

**Comment by bmegli** [comment]
Hi there @mob41,

First note - I am in no way responsible for the bindings.

I had recently similiar problem where I needed to use C++ bindints with I2C device that needs manual creation (no autodetection).

In my fork I ended up adding 2 parameters constructor, for i2c_sensor (apart from 1 parameter)

``` C++
i2c_sensor(address_type address = INPUT_AUTO, const std::set<sensor_type> &type={} );
```

See [commit](https://github.com/bmegli/ev3dev-lang-cpp/commit/41d7510e5c7e95e1e4c5a2fb67490d151456ea94) for the details.

Then I instantiate the i2c_sensor with different driver like [here](https://github.com/bmegli/ev3dev-mapping-modules/blob/master/ev3dead-reconning/main.cpp#L85):

``` C++
ev3dev::i2c_sensor gyro(GYRO_PORT, {"mi-xg1300l"});
```

I think that such constructor is needed for all i2c devices that specify different driver but I may be wrong, let's wait and see what the bindings team thinks.

This probably goes to @WasabiFan  and @ddemidov at least?

Edit: updated code link

**Comment by bmegli** [comment]
So my solution would be probably along the line:
1.   Add constructor to i2c_sensor that takes port and driver
2.   Use this constructor when instantating derived class, the derived class has 1 param constructor but calls base 2 param constructor with port and correct driver.

**Comment by a1aw** [comment]
That's a good idea, but I still want to see what @WasabiFan , @ddemidov would do.

**Comment by WasabiFan** [comment]
It looks like [my implementation](https://github.com/WasabiFan/ev3dev-lang-js/blob/master/src/sensors.ts#L367) accepts an optional string array of driver names, and if none is provided just uses the port name to choose a device. That seems like a reasonable behavior.

**Comment by a1aw** [comment]
So that I will overload the constructor to support a optional string of driver name. Thanks!
