### ISSUE TITLE
Dual motors

### ISSUE THREAD

**Issue by absentdream** [ev3dev/ev3dev-lang#176]
anyone got any examples of how to drive 2 motors at same time (aka tank control).

**Comment by dwalton76** [comment]
In python...see the Tank classes here:
https://github.com/rhempel/ev3dev-lang-python/blob/develop/ev3dev/helper.py

and here is TRACK3R using those classes
https://github.com/rhempel/ev3dev-lang-python/blob/develop/demo/TRACK3R/TRACK3R.py

**Comment by dwalton76** [comment]
Updating the links....`MoveTank` class
https://github.com/rhempel/ev3dev-lang-python/blob/develop/ev3dev/motor.py#L1515

`RemoteControlledTank` is a child of `MoveTank`
https://github.com/rhempel/ev3dev-lang-python/blob/develop/ev3dev/control/rc_tank.py#L11

TRACK3R using `RemoteControlledTank`
https://github.com/ev3dev/ev3dev-lang-python-demo/tree/master/robots/TRACK3R
