### ISSUE TITLE
Use submodules?

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev-lang#30]
I would like to use the vala bindings for ev3dev/ev3dev#169 (so you can expect a pull request to update it to the current kernel). It would be nice if each language had its own submodule so that I can clone only the language that I want to use instead of having to clone everything.

For now though, I am going to try this: http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/

**Comment by WasabiFan** [comment]
@bmegli I recommend that you submodule-ify your R binding as well. If you separate yours like @dlech and I did, you will have full control over your code and won't have to operate through pull requests.

**Comment by WasabiFan** [comment]
I think we can close this now -- we have transitioned a few of the libraries into submodules and they are serving their purpose well.
