### ISSUE TITLE
documentation says "space separated" when it should be "array"

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev-lang#94]
There are a number of places where the docs say a "space separated list". This is copied from the sysfs documentation, but in ev3dev-lang, these are actually arrays of strings.

**Comment by ddemidov** [comment]
What do you think of replacing all occurrences of `space separated list` with just `list`. It sounds better to me than `array of strings` in e.g.

```
Returns a list of commands that are supported by the motor controller.
```

**Comment by WasabiFan** [comment]
@ddemidov I like that -- "list" should be a drop-in replacement in pretty much all cases.

**Comment by ddemidov** [comment]
Should be fixed now.

**Comment by dlech** [comment]
Looks good!
